#!/usr/bin/env node
// dod-index.mjs — index and verify Definition-of-Done plans. No dependencies. Node 20+.
//
//   node dod-index.mjs [--dir <store>]        regenerate <store>/README.md, print a summary
//   node dod-index.mjs --list                 read-only listing of every plan (no write)
//   node dod-index.mjs --brief                one line for a session-start hook (never exits non-zero)
//   node dod-index.mjs --check <slug>         verify one plan's invariants; exit 1 on any violation
//   node dod-index.mjs --check-index          exit 1 if README.md is missing or stale
//   node dod-index.mjs --selftest             prove the checks block known-bad plans and pass a known-good one
//                                             (mutates DOD_TEST_SECRET for the process — run it in its own process,
//                                             as npm run validate and CI do; two selftests in one process race)
//
// Store resolution: --dir, else a `dod-store: <path>` line in ./CLAUDE.md, ./AGENTS.md or ./.cursor/rules/dod.mdc
// (conflicting declarations are an error), else docs/dod. Grammar is defined in ../references/plan-template.md.
// In grammar-controlled sections (Definition of Done, Baseline, Coverage, Assumptions, Amendments, Children, Log)
// a bullet or table row that does not match the grammar is a problem, not prose.

import { closeSync, existsSync, mkdirSync, mkdtempSync, openSync, readdirSync, readFileSync, readSync, realpathSync, rmSync, statSync, writeFileSync } from "node:fs";
import { randomBytes } from "node:crypto";
import { homedir, tmpdir } from "node:os";
import { basename, join, resolve, relative, sep } from "node:path";
import { fileURLToPath } from "node:url";

const SELF = fileURLToPath(import.meta.url);
const MARKER = "<!-- generated by dod-index.mjs — do not edit; regenerate with: node <skill>/scripts/dod-index.mjs -->";
const STATUSES = ["draft", "ready", "in-progress", "done", "cancelled", "superseded"];
const REVIEWERS = ["codex", "subagent", "human"];
const SIZES = ["S", "M", "L", "Epic"];
const PAST_DRAFT = ["ready", "in-progress", "done"];
const TERMINAL = ["done", "cancelled", "superseded"];
const GATING = ["2.1", "3.3", "4.4", "6.2", "10.1", "10.3", "14.3"];
// canonical layers: name and probe count, from references/layers.md
const LAYERS = [
  ["Purpose & typical use", 3], ["Actors & permissions", 3], ["Inputs, outputs & data", 4], ["Business rules & invariants", 4],
  ["Internal interfaces", 3], ["External dependencies & contracts", 3], ["States & lifecycle", 3], ["Minimal stretch", 2],
  ["Maximal stretch", 3], ["Security & privacy", 4], ["Design & UX", 3], ["Failure handling & observability", 3],
  ["Performance & scale", 2], ["Rollout & compatibility", 3], ["Out of scope", 2],
];
const REQUIRED_FM = ["dod", "id", "slug", "title", "status", "size", "parent", "created", "baselined", "closed", "commit", "coverage_author", "coverage_reviewer", "review"];
// legal transitions: to → allowed from; and the exact command each transition line must carry (B12)
const CMD = {
  draft: /^plan$/, ready: /^approve(?: · review: (?:codex|subagent|human))?$/, done: /^close$/,
  cancelled: /^cancel · \S.*$/, superseded: /^supersede · by ([a-z0-9]+(?:-[a-z0-9]+)*)$/,
  start: /^start$/, reopen: /^reopen (A\d+)$/,
};
const LEGAL = { draft: [null], ready: ["draft"], "in-progress": ["ready", "done"], done: ["in-progress"], cancelled: ["draft", "ready", "in-progress"], superseded: ["draft", "ready", "in-progress"] };

const RE = {
  item: /^- \[( |x|X)\] (D\d+) · (.+?) · (test|cmd|file|manual): (.*)$/,
  amendment: /^- (A\d+) · (\d{4}-\d{2}-\d{2}) · (discovered|requested|defect|external) · (.+?) · layer: ([^·]+?) · (.+)$/,
  op: /^([+~-])(D\d+)$/,
  transition: /^- (\d{4}-\d{2}-\d{2}) · status → ([a-z-]+)(?: · (.*))?$/,
  evidence: /^- (\d{4}-\d{2}-\d{2}) · (D\d+) · (pass|fail) · (test|cmd|file|manual): (.+?) · ([^·]+?) · ([^·]+?)$/,
  child: /^- ([a-z0-9]+(?:-[a-z0-9]+)*) · (planned|in-progress|done)\s*$/,
  assumption: /^- (A-\d+) · (validated|reversible|decision-required) · (.+)$/,
  coverage: /^\| (\d{1,2}) \| ([^|]+?) \| (Considered|Gap|N\/A) \| ([^|]*?) \| ([^|]*?) \|\s*$/,
  gate: /^Gate — acceptance & testability: (passed|failed)\b/,
  verdict: /^VERDICT: (READY|REVISE)\s*$/,
  reviewHead: /^## Review (\d+) · (\d{4}-\d{2}-\d{2}) · (codex|subagent|human)\b/,
  finding: /^(?:\d+\.\s*|-\s*)?\**F(\d+)\b/,
  disposition: /^- F(\d+) · (accepted|rejected) · /,
  coverageLine: /^(\d+)\/(\d+) layers · (\d+)\/(\d+) probes$/,
};

const validDate = (s) => /^\d{4}-\d{2}-\d{2}$/.test(s) && !Number.isNaN(Date.parse(s)) && new Date(s).toISOString().slice(0, 10) === s;

// ---------------------------------------------------------------- parsing

export function parsePlan(text, file = "<memory>") {
  const plan = { file, slug: basename(file, ".md"), fm: {}, sections: {}, headings: [], items: [], baseline: [], amendments: [], transitions: [], evidence: [], children: [], assumptions: [], coverage: [], gate: null, parseErrors: [], reviews: [] };
  const lines = text.split(/\r?\n/);
  let i = 0;
  if (lines[0] !== "---") { plan.parseErrors.push("no frontmatter"); return plan; }
  for (i = 1; i < lines.length && lines[i] !== "---"; i++) {
    const m = lines[i].match(/^([a-z_]+):\s*(.*)$/);
    if (m) plan.fm[m[1]] = m[2].trim();
    else if (lines[i].trim()) plan.parseErrors.push(`frontmatter line ${i + 1} is not key: value`);
  }
  if (i >= lines.length) { plan.parseErrors.push("frontmatter not closed"); return plan; }
  let current = "";
  for (i = i + 1; i < lines.length; i++) {
    const line = lines[i];
    const h = line.match(/^(##+) (.+?)\s*$/);
    if (h) {
      const name = h[2].replace(/\s*·.*$/, "").replace(/\s*\(.*\)\s*$/, "").trim();
      plan.headings.push(name);
      if (h[1] === "##") { current = name; plan.sections[current] = plan.sections[current] ?? []; continue; }
    }
    if (current) plan.sections[current].push(line);
  }
  const sec = (name) => plan.sections[name] ?? [];
  const bad = (section, l) => plan.parseErrors.push(`${section}: line does not match the grammar: ${l.slice(0, 70)}`);
  const item = (m) => ({ checked: m[1] !== " ", id: m[2], statement: m[3], type: m[4], detail: m[5], line: `${m[2]} · ${m[3]} · ${m[4]}: ${m[5]}` });
  for (const l of sec("Definition of Done")) { const m = l.match(RE.item); if (m) plan.items.push(item(m)); else if (/^- /.test(l)) bad("Definition of Done", l); }
  for (const l of sec("Baseline")) { const m = l.match(RE.item); if (m) plan.baseline.push(item(m)); else if (/^- /.test(l)) bad("Baseline", l); }
  for (const l of sec("Amendments")) {
    const m = l.match(RE.amendment);
    if (m) plan.amendments.push({ id: m[1], n: Number(m[1].slice(1)), date: m[2], kind: m[3], ops: m[4].trim().split(/\s+/), layer: m[5].trim(), why: m[6] });
    else if (/^- /.test(l)) bad("Amendments", l);
  }
  let seq = 0;
  for (const l of sec("Log")) {
    let m = l.match(RE.transition); if (m) { plan.transitions.push({ seq: seq++, date: m[1], status: m[2], detail: m[3] ?? "" }); continue; }
    m = l.match(RE.evidence); if (m) { plan.evidence.push({ seq: seq++, date: m[1], id: m[2], result: m[3], type: m[4], detail: m[5], commit: m[6].trim(), who: m[7].trim() }); continue; }
    if (/^- /.test(l) && !/^- \d{4}-\d{2}-\d{2} · (review skipped|renamed from|note) /.test(l)) bad("Log", l);
  }
  for (const l of sec("Children")) { const m = l.match(RE.child); if (m) plan.children.push({ slug: m[1], status: m[2] }); else if (/^- /.test(l)) bad("Children", l); }
  for (const l of sec("Assumptions")) {
    const m = l.match(RE.assumption);
    if (!m) { if (/^- /.test(l)) bad("Assumptions", l); continue; }
    if (m[2] === "validated" && !/ · source: \S/.test(m[3])) bad("Assumptions", `${l}  (validated needs \` · source: <path / doc / who confirmed>\`)`);
    if (m[2] === "reversible" && !/ · fallback: \S/.test(m[3])) bad("Assumptions", `${l}  (reversible needs \` · fallback: <what changes if wrong>\`)`);
    plan.assumptions.push({ id: m[1], type: m[2] });
  }
  for (const l of sec("Coverage")) {
    const m = l.match(RE.coverage);
    if (m) { plan.coverage.push({ n: Number(m[1]), layer: m[2].trim(), status: m[3], probes: m[4].trim(), pointer: m[5].trim() }); continue; }
    const g = l.match(RE.gate); if (g) { plan.gate = g[1]; continue; }
    if (/^\|/.test(l) && !/^\| #/.test(l) && !/^\|-/.test(l)) bad("Coverage", l);
  }
  return plan;
}

export function parseReviews(text) {
  const reviews = [];
  let inDisp = false;
  for (const l of text.split(/\r?\n/)) {
    let m = l.match(RE.reviewHead);
    if (m) { reviews.push({ n: Number(m[1]), date: m[2], reviewer: m[3], verdict: null, findings: new Set(), dispositions: new Set(), coverage: null }); inDisp = false; continue; }
    if (!reviews.length) continue;
    const r = reviews.at(-1);
    if (/^### Dispositions/.test(l)) { inDisp = true; continue; }
    m = l.match(RE.verdict); if (m) { r.verdict = m[1]; continue; }
    m = l.match(RE.coverageLine); if (m) { r.coverage = l.trim(); continue; }
    if (inDisp) { m = l.match(RE.disposition); if (m) r.dispositions.add(m[1]); continue; }
    m = l.match(RE.finding); if (m) r.findings.add(m[1]);
  }
  return reviews;
}

export function loadPlans(dir) {
  if (!existsSync(dir)) return [];
  const plans = readdirSync(dir)
    .filter((f) => f.endsWith(".md") && f !== "README.md" && f !== "profile.md" && !f.endsWith(".reviews.md"))
    .sort()
    .map((f) => parsePlan(readFileSync(join(dir, f), "utf8"), join(dir, f)));
  for (const p of plans) {
    const rf = join(dir, `${p.slug}.reviews.md`);
    p.reviews = existsSync(rf) ? parseReviews(readFileSync(rf, "utf8")) : [];
  }
  return plans;
}

// ---------------------------------------------------------------- checks

export function coverageLine(rows) {
  const applicable = rows.filter((r) => r.status !== "N/A");
  const considered = applicable.filter((r) => r.status === "Considered");
  let pd = 0, pn = 0;
  for (const r of applicable) { const m = r.probes.match(/^(\d+)\/(\d+)$/); if (m) { pn += Number(m[1]); pd += Number(m[2]); } }
  return `${considered.length}/${applicable.length} layers · ${pn}/${pd} probes`;
}

export function checkPlan(plan, all = [plan]) {
  const problems = [];
  const warnings = [];
  const fm = plan.fm;
  const status = fm.status;
  const past = PAST_DRAFT.includes(status);
  if (plan.parseErrors.length) problems.push(...plan.parseErrors);

  // 0. frontmatter
  for (const k of REQUIRED_FM) if (!(k in fm)) problems.push(`frontmatter is missing ${k}`);
  if (!STATUSES.includes(status)) problems.push(`status "${status}" is not one of ${STATUSES.join(", ")}`);
  if (fm.size && !SIZES.includes(fm.size)) problems.push(`size "${fm.size}" is not one of ${SIZES.join(", ")}`);
  if (fm.slug && fm.slug !== plan.slug) problems.push(`frontmatter slug "${fm.slug}" ≠ filename "${plan.slug}"`);
  if (fm.id && !/^dod-\d{8}-[a-z0-9]{4}$/.test(fm.id)) problems.push(`id "${fm.id}" is not dod-YYYYMMDD-xxxx`);
  if (fm.id) { const twin = all.find((p) => p !== plan && p.fm.id === fm.id); if (twin) problems.push(`id ${fm.id} is also used by ${twin.slug} — ids are unique per store`); }
  for (const k of ["created", "baselined", "closed"]) if (fm[k] && fm[k] !== "none" && !validDate(fm[k])) problems.push(`${k} "${fm[k]}" is not a valid YYYY-MM-DD`);
  if (fm.created === "none") problems.push("created cannot be none");
  if (fm.coverage_author && fm.coverage_author !== "pending" && !RE.coverageLine.test(fm.coverage_author)) problems.push(`coverage_author "${fm.coverage_author}" is not "a/b layers · c/d probes"`);
  if (fm.coverage_reviewer && fm.coverage_reviewer !== "pending" && !RE.coverageLine.test(fm.coverage_reviewer)) problems.push(`coverage_reviewer "${fm.coverage_reviewer}" is not "a/b layers · c/d probes"`);
  const review = fm.review ?? "pending";
  if (review !== "pending" && !REVIEWERS.includes(review)) problems.push(`review "${review}" must be pending, ${REVIEWERS.join(", ")}`);

  const ids = plan.items.map((x) => x.id);
  const dupes = ids.filter((x, k) => ids.indexOf(x) !== k);
  if (dupes.length) problems.push(`duplicate DoD ids: ${[...new Set(dupes)].join(", ")}`);
  const byId = new Map(plan.items.map((x) => [x.id, x]));

  // 1. coverage table: canonical rows, probe totals, pointers resolve, D-item mapping for 2–14; gate
  if (plan.coverage.length) {
    if (plan.coverage.length !== LAYERS.length) problems.push(`Coverage table has ${plan.coverage.length} rows, expected ${LAYERS.length}`);
    plan.coverage.forEach((r, k) => {
      const canon = LAYERS[k];
      if (!canon) return;
      if (r.n !== k + 1) problems.push(`Coverage row ${k + 1} is numbered ${r.n} — rows must be 1–15 in order`);
      if (r.layer !== canon[0]) problems.push(`Coverage row ${k + 1} is "${r.layer}", expected "${canon[0]}"`);
      if (r.status === "N/A") { if (r.pointer.length < 12) problems.push(`layer ${r.n} is N/A without an applicability test`); return; }
      const m = r.probes.match(/^(\d+)\/(\d+)$/);
      if (!m) problems.push(`layer ${r.n} probes "${r.probes}" is not n/n`);
      else {
        if (Number(m[2]) !== canon[1]) problems.push(`layer ${r.n} claims ${m[2]} probes; the rubric has ${canon[1]} — denominators are fixed; a probe you examined and found inapplicable is still answered (state the test in the section)`);
        if (Number(m[1]) > Number(m[2])) problems.push(`layer ${r.n} probes ${r.probes}: numerator exceeds denominator`);
        if (r.status === "Considered" && m[1] !== m[2]) problems.push(`layer ${r.n} is Considered with ${r.probes} probes — Considered means every applicable probe`);
        if (r.status === "Gap" && m[1] === m[2]) problems.push(`layer ${r.n} is Gap with all probes answered — mark it Considered or fix the count`);
      }
      if (r.status === "Considered") {
        const head = r.pointer.split("›")[0].trim().toLowerCase();
        if (!head) problems.push(`layer ${r.n} is Considered without a pointer`);
        else if (!plan.headings.some((h) => h.toLowerCase() === head || h.toLowerCase().startsWith(head))) problems.push(`layer ${r.n} pointer "${r.pointer.split("›")[0].trim()}" does not name a heading in this plan`);
        if (r.n >= 2 && r.n <= 14) {
          const refs = [...r.pointer.matchAll(/\bD\d+\b/g)].map((x) => x[0]);
          if (!refs.length) problems.push(`layer ${r.n} is Considered but its pointer names no D-item (acceptance gate: every Considered layer 2–14 → ≥ 1 item, e.g. "Security › D4, D7")`);
          for (const d of refs) if (!byId.has(d)) problems.push(`layer ${r.n} pointer references ${d}, which is not a current item`);
        }
      }
    });
  }
  if (past) {
    if (!plan.coverage.length) problems.push(`status ${status} but no parseable Coverage table`);
    const gaps = plan.coverage.filter((r) => r.status === "Gap").map((r) => r.n);
    if (gaps.length) problems.push(`status ${status} with Gap layers: ${gaps.join(", ")}`);
    if (plan.gate !== "passed") problems.push(`status ${status} but the acceptance gate line is ${plan.gate ?? "missing"}`);
    if (plan.coverage.length === LAYERS.length && fm.coverage_author && fm.coverage_author !== coverageLine(plan.coverage)) problems.push(`coverage_author "${fm.coverage_author}" ≠ table "${coverageLine(plan.coverage)}"`);
    if (fm.coverage_reviewer === "pending") problems.push(`status ${status} but coverage_reviewer is pending`);
  }

  // 2. amendments: ids sequential, dates valid and nondecreasing, ops strict, IDs never reused
  const everSeen = new Set(plan.baseline.map((b) => b.id));
  const baseById = new Map(plan.baseline.map((b) => [b.id, b]));
  const expected = new Set(everSeen);
  const changedAt = new Map(); // id → date of last ~ or +
  let discoveredOps = 0, lastDate = "", lastN = 0;
  let lastMaterialReviewTrigger = null; // date of last amendment that requires re-review (gating probe or removal)
  for (const a of plan.amendments) {
    if (a.n !== lastN + 1) problems.push(`${a.id}: amendment ids must be sequential (expected A${lastN + 1})`);
    lastN = a.n;
    if (!validDate(a.date)) problems.push(`${a.id}: date "${a.date}" is not valid`);
    else if (a.date < lastDate) problems.push(`${a.id}: date ${a.date} is earlier than the previous amendment`);
    lastDate = a.date > lastDate ? a.date : lastDate;
    let designOps = 0, removal = false;
    if (!(a.ops.length === 1 && a.ops[0] === "—")) for (const tok of a.ops) {
      const m = tok.match(RE.op);
      if (!m) { problems.push(`${a.id}: op "${tok}" is not +Dn, -Dn, ~Dn or —`); continue; }
      const [, op, id] = m;
      if (op === "+") { if (everSeen.has(id)) problems.push(`${a.id}: +${id} but ${id} was already used — IDs are never reused`); everSeen.add(id); expected.add(id); changedAt.set(id, a.date); designOps++; }
      else if (op === "-") { if (!expected.has(id)) problems.push(`${a.id}: -${id} but ${id} does not exist at that point`); expected.delete(id); removal = true; }
      else { if (!expected.has(id)) problems.push(`${a.id}: ~${id} but ${id} does not exist at that point`); changedAt.set(id, a.date); designOps++; }
    }
    if (a.kind === "discovered") { discoveredOps += Math.max(1, designOps); if (!/^\d{1,2}(\.\d)?$/.test(a.layer)) problems.push(`${a.id}: discovered amendments must name the layer or probe (e.g. 7 or 7.2), got "${a.layer}"`); }
    if (GATING.includes(a.layer) || removal) lastMaterialReviewTrigger = a;
  }
  if (past) {
    if (!plan.baseline.length) problems.push(`status ${status} but ## Baseline is empty`);
    else {
      const cur = new Set(ids);
      const missing = [...expected].filter((x) => !cur.has(x));
      const extra = [...cur].filter((x) => !expected.has(x));
      if (missing.length || extra.length) problems.push(`amendment drift — current DoD ≠ baseline + amendments (missing: ${missing.join(", ") || "none"}; unexplained: ${extra.join(", ") || "none"})`);
      for (const it of plan.items) {
        const b = baseById.get(it.id);
        if (b && !changedAt.has(it.id) && b.line !== it.line) problems.push(`${it.id} differs from ## Baseline without a ~${it.id} amendment`);
      }
    }
  }

  // 3. evidence: type matches; pass after last fail (Log order) and on/after the item's last amendment
  const verified = new Set();
  for (const e of plan.evidence) {
    if (!validDate(e.date)) problems.push(`evidence for ${e.id}: date "${e.date}" is not valid`);
    const it = byId.get(e.id);
    if (!it) { warnings.push(`evidence for ${e.id}, which is not a current item`); continue; }
    if (e.type !== it.type) problems.push(`${e.id} evidence type "${e.type}" ≠ item type "${it.type}"`);
  }
  for (const it of plan.items) {
    const ev = plan.evidence.filter((e) => e.id === it.id);
    const lastFail = ev.filter((e) => e.result === "fail").at(-1);
    const since = changedAt.get(it.id) ?? "";
    const pass = ev.filter((e) => e.result === "pass" && e.type === it.type && (!lastFail || e.seq > lastFail.seq) && e.date >= since).at(-1);
    if (pass) verified.add(it.id);
    if (it.checked && !pass) problems.push(`${it.id} is checked without evidence (no pass after the last fail${since ? ` and after its amendment on ${since}` : ""})`);
  }

  // 4. review: reviews file, READY on record with findings dispositioned, re-review after gating / removal amendments
  const readyReviews = plan.reviews.filter((r) => r.verdict === "READY");
  for (const r of plan.reviews) {
    if (!validDate(r.date)) problems.push(`Review ${r.n}: date "${r.date}" is not valid`);
    if (!r.verdict) problems.push(`Review ${r.n} has no VERDICT line`);
    const undisposed = [...r.findings].filter((f) => !r.dispositions.has(f));
    if (undisposed.length) problems.push(`Review ${r.n}: findings without a disposition: F${undisposed.join(", F")}`);
    if (r.verdict === "READY" && !r.coverage) problems.push(`Review ${r.n} is READY but has no reviewer coverage line`);
  }
  plan.reviews.forEach((r, k) => {
    if (r.n !== k + 1) problems.push(`Review ${r.n}: reviews must be numbered sequentially (expected Review ${k + 1})`);
    if (k && r.date < plan.reviews[k - 1].date) problems.push(`Review ${r.n} is dated before Review ${plan.reviews[k - 1].n}`);
  });
  const lastReview = plan.reviews.at(-1);
  const lastReady = readyReviews.at(-1);
  if ((status === "ready" || status === "done") && review === "pending") problems.push(`status ${status} but review is pending`);
  if (past && review !== "pending") {
    if (!readyReviews.length) problems.push(`review is ${review} but ${plan.slug}.reviews.md has no VERDICT: READY`);
    else {
      // the review on record is the LATEST one — a later REVISE cancels an earlier READY
      if (lastReview.verdict !== "READY") problems.push(`review is ${review} but the latest review (Review ${lastReview.n}) is ${lastReview.verdict ?? "without a verdict"} — set review: pending until a later READY`);
      if (lastReady.reviewer !== review) problems.push(`review: ${review} but the latest READY review (Review ${lastReady.n}) was by ${lastReady.reviewer}`);
      if (lastReady.coverage && fm.coverage_reviewer !== lastReady.coverage) problems.push(`coverage_reviewer "${fm.coverage_reviewer}" ≠ Review ${lastReady.n}'s line "${lastReady.coverage}"`);
      if (fm.baselined !== "none" && validDate(fm.baselined) && !readyReviews.some((r) => r.date <= fm.baselined)) problems.push(`no READY review dated on/before the baseline date ${fm.baselined}`);
    }
  }
  if (status === "in-progress" && review === "pending") warnings.push("review is pending (re-opened by an amendment?) — approve before close");
  if (lastMaterialReviewTrigger && !readyReviews.some((r) => r.date >= lastMaterialReviewTrigger.date)) {
    const a = lastMaterialReviewTrigger;
    if (status === "done") problems.push(`${a.id} (${GATING.includes(a.layer) ? `gating probe ${a.layer}` : "removes a baseline item"}) has no READY review dated on/after it`);
    else if (review !== "pending") problems.push(`${a.id} (${GATING.includes(a.layer) ? `gating probe ${a.layer}` : "removes a baseline item"}) requires review: pending until re-approved`);
  }

  // 5. done: everything verified, report present; epics: ≥1 child, all done
  if (status === "done") {
    const open = plan.items.filter((it) => !it.checked || !verified.has(it.id)).map((it) => it.id);
    if (open.length) problems.push(`status done but unverified items: ${open.join(", ")}`);
    if (!(plan.sections["Report"] ?? []).some((l) => l.trim())) problems.push("status done but ## Report is empty");
  }
  if (fm.size === "Epic") {
    if (!plan.children.length) problems.push("Epic with no children under ## Children");
    for (const c of plan.children) {
      const child = all.find((p) => p.slug === c.slug);
      if (!child) { (status === "done" ? problems : warnings).push(`child ${c.slug} has no plan file`); continue; }
      if (status === "done" && child.fm.status !== "done") problems.push(`child ${c.slug} is ${child.fm.status}, not done`);
      const actual = child.fm.status === "done" ? "done" : child.fm.status === "in-progress" ? "in-progress" : "planned";
      if (actual !== c.status) warnings.push(`child ${c.slug} manifest says ${c.status}, plan says ${child.fm.status}`);
    }
  } else if (plan.children.length) problems.push("## Children is only for size Epic");
  if (fm.parent && fm.parent !== "none") {
    const parent = all.find((p) => p.slug === fm.parent);
    if (!parent) problems.push(`parent ${fm.parent} not found in the store`);
    else { if (parent.fm.size !== "Epic") problems.push(`parent ${fm.parent} is not an Epic`); if (!parent.children.some((c) => c.slug === plan.slug)) problems.push(`parent ${fm.parent} does not list ${plan.slug} under ## Children`); }
  }

  // 6. lifecycle replay
  let prev = null, prevDate = "";
  for (const t of plan.transitions) {
    if (!validDate(t.date)) problems.push(`transition to ${t.status}: date "${t.date}" is not valid`);
    else if (t.date < prevDate) problems.push(`transition to ${t.status} on ${t.date} is dated before the previous transition`);
    prevDate = t.date > prevDate ? t.date : prevDate;
    const from = LEGAL[t.status];
    if (!from) { problems.push(`unknown transition target "${t.status}"`); prev = t.status; continue; }
    if (!from.includes(prev)) problems.push(`illegal transition ${prev ?? "(start)"} → ${t.status}`);
    if (t.status === "in-progress" && prev === "done") {
      const m = t.detail.match(CMD.reopen);
      const a = m && plan.amendments.find((x) => x.id === m[1]);
      if (!m) problems.push("reopen must cite its amendment: `status → in-progress · reopen A<n>`");
      else if (!a) problems.push(`reopen cites ${m[1]}, which does not exist`);
      else if (a.date > t.date) problems.push(`reopen cites ${m[1]}, dated after the reopen`);
    } else if (t.status === "in-progress") {
      if (!CMD.start.test(t.detail)) problems.push("ready → in-progress must read `status → in-progress · start`");
    } else if (t.status === "cancelled") {
      if (!CMD.cancelled.test(t.detail)) problems.push("cancelled transition must read `status → cancelled · cancel · <reason>`");
    } else if (t.status === "superseded") {
      const m = t.detail.match(CMD.superseded);
      if (!m) problems.push("superseded transition must read `status → superseded · supersede · by <slug>`");
      else if (!all.find((p) => p.slug === m[1])) problems.push(`superseded by ${m[1]}, which is not in the store`);
    } else if (CMD[t.status] && !CMD[t.status].test(t.detail)) problems.push(`transition to ${t.status} must read \`status → ${t.status} · ${t.status === "draft" ? "plan" : t.status === "ready" ? "approve" : "close"}\``);
    prev = t.status;
  }
  const reachedReady = plan.transitions.some((t) => t.status === "ready");
  if (!plan.transitions.length) problems.push("no status transition in ## Log");
  else if (prev !== status) problems.push(`frontmatter status "${status}" ≠ last Log transition "${prev}"`);
  // baselined follows history, not the current state: a cancelled plan that was once ready keeps its baseline (B3)
  const shouldHaveBaseline = past || reachedReady;
  if (shouldHaveBaseline && (fm.baselined ?? "none") === "none") problems.push(`status ${status} but baselined is none${past ? "" : " (the plan reached ready; the baseline is never removed)"}`);
  if (!shouldHaveBaseline && fm.baselined && fm.baselined !== "none") problems.push(`status ${status} but baselined is set — the plan never reached ready`);
  if (TERMINAL.includes(status) && (fm.closed ?? "none") === "none") problems.push(`status ${status} but closed is none`);
  if (!TERMINAL.includes(status) && fm.closed && fm.closed !== "none") problems.push(`status ${status} but closed is set`);

  // 7. decision-required assumptions block anything past draft
  const dr = plan.assumptions.filter((a) => a.type === "decision-required").length;
  if (dr && status !== "draft") problems.push(`${dr} decision-required assumption(s) while status is ${status}`);

  return { problems, warnings, verified: verified.size, total: plan.items.length, report: reportNumbers(plan, discoveredOps) };
}

export function reportNumbers(plan, discoveredOps) {
  const B = plan.baseline.length;
  const kinds = { discovered: 0, requested: 0, defect: 0, external: 0 };
  const missed = {};
  for (const a of plan.amendments) { kinds[a.kind]++; if (a.kind === "discovered") missed[a.layer] = (missed[a.layer] ?? 0) + 1; }
  // discovered counts design changes (+/~ ops on D-items), so bundling several into one amendment does not lower it
  const G = discoveredOps ?? plan.amendments.filter((a) => a.kind === "discovered").reduce((n, a) => n + Math.max(1, a.ops.filter((o) => /^[+~]/.test(o)).length), 0);
  const rate = B ? Math.round((B / (B + G)) * 100) : null;
  return { baseline: B, discoveredDesign: G, ...kinds, rate, missed };
}

// ---------------------------------------------------------------- index / list

export function renderIndex(plans, dir, opts = {}) {
  const checks = new Map(plans.map((p) => [p.slug, checkPlan(p, plans)]));
  const rows = plans.map((p) => {
    const c = checks.get(p.slug);
    const r = c.report;
    const cwe = c.problems.filter((x) => / is checked without evidence/.test(x)).length;
    const flag = c.problems.length ? ` ⚠ ${c.problems.length}` : "";
    return `| [${p.slug}](${p.slug}.md) | ${p.fm.title ?? ""} | ${p.fm.status ?? "?"}${flag} | ${p.fm.size ?? ""} | ${c.verified}/${c.total}${cwe ? ` (+${cwe} unverified ✓)` : ""} | ${r.baseline || "—"} | ${r.rate == null ? "—" : r.rate + " %"} | ${p.fm.parent && p.fm.parent !== "none" ? p.fm.parent : ""} |`;
  });
  const done = plans.filter((p) => p.fm.status === "done").map((p) => checks.get(p.slug).report).filter((r) => r.baseline > 0);
  const sumB = done.reduce((s, r) => s + r.baseline, 0);
  const sumG = done.reduce((s, r) => s + r.discoveredDesign, 0);
  const agg = sumB ? Math.round((sumB / (sumB + sumG)) * 100) : null;
  const missedDone = {}, missedOpen = {};
  for (const p of plans) for (const [layer, n] of Object.entries(checks.get(p.slug).report.missed)) { const t = p.fm.status === "done" ? missedDone : missedOpen; t[layer] = (t[layer] ?? 0) + n; }
  const fmt = (m) => Object.entries(m).sort((a, b) => b[1] - a[1]).slice(0, 5).map(([l, n]) => `layer ${l} (${n})`).join(", ") || "none";
  const open = plans.filter((p) => ["ready", "in-progress"].includes(p.fm.status)).length;
  const text = [
    MARKER,
    "# Definition of Done — index",
    "",
    `${plans.length} plan(s) · ${open} open · ${done.length} done` + (agg == null ? "" : ` · prediction rate across done plans ${agg} % (${sumB} baseline items / ${sumG} discovered design changes; target ≥ 90 %)`),
    "",
    "| Plan | Title | Status | Size | Verified | Baseline items | Prediction | Parent |",
    "|---|---|---|---|---|---|---|---|",
    ...rows,
    "",
    `Most-missed layers — done plans: ${fmt(missedDone)}; open plans (provisional): ${fmt(missedOpen)}.`,
    "",
    `${storeFooter(dir, opts)} Plans are the source of truth; this file is regenerated.`,
    "",
  ].join("\n");
  if (renderSink) renderSink.push(text);
  return text;
}

// The footer never carries an absolute path: it is the store's position relative to the working directory
// (`.` when they coincide), rendered with posix separators. A store on another root (drive letter, UNC share)
// has no relative position, so the footer carries no path at all. The one interpolated value passes through
// one escaping rule: backtick → ', control characters, line separators and Unicode format characters → space.
const ABS_START = /^(?:[A-Za-z]:[\\/]|[\\/])/;
const FOOTER_NO_PATH = "Store: outside the working directory (see the dod-store: line in your instructions file).";
function storeFooter(dir, opts = {}) {
  const rel = opts.relative ?? relative;
  const r = rel(opts.cwd ?? process.cwd(), dir);
  if (ABS_START.test(r)) return FOOTER_NO_PATH;
  const p = (r.split(sep).join("/") || ".").replace(/`/g, "'").replace(/[\u0000-\u001F\u007F-\u009F\u2028\u2029\p{Cf}]/gu, " ");
  return `Store: \`${p}\`.`;
}

// Names of the needles whose value occurs in text as a path of its own — an occurrence preceded by `.`, `/` or
// `\` continues a relative path (`../../tmp/x` legitimately contains `/tmp/x`) and is not a leak. Values, never
// names, are what must not leak, so callers report the names only.
export function scanForLeaks(text, needles) {
  const slashes = (t) => t.replace(/\\/g, "/"); // the footer renders posix separators, so a Windows needle must match in that form too
  const hay = slashes(text);
  const leaked = (v) => { for (let i = hay.indexOf(v); i !== -1; i = hay.indexOf(v, i + 1)) if (i === 0 || !"./".includes(hay[i - 1])) return true; return false; };
  return Object.entries(needles).filter(([, v]) => typeof v === "string" && v.length > 0 && leaked(slashes(v))).map(([k]) => k);
}

// Classify the store's existing README.md footer: "absolute" (written by dod ≤ 0.1.2, leaks the developer's
// filesystem layout), "oversize" (> 1 MB — not a generated index), "unreadable" (with the error code), or "ok"
// (relative, missing, or no footer line — freshness handles those). Bounded read from a descriptor, so a file
// that grows between stat and read is still capped; invalid UTF-8 decodes to U+FFFD and is judged as decoded.
const INDEX_CAP = 1024 * 1024;
export const fsio = { statSync, openSync, readSync, closeSync };
function legacyFooter(dir) {
  const f = join(dir, "README.md");
  let fd;
  try {
    const st = fsio.statSync(f, { throwIfNoEntry: false });
    if (!st) return { kind: "ok" };
    if (st.size > INDEX_CAP) return { kind: "oversize" };
    fd = fsio.openSync(f, "r");
    const buf = Buffer.alloc(INDEX_CAP + 1);
    let n = 0, got;
    while (n < buf.length && (got = fsio.readSync(fd, buf, n, buf.length - n, null)) > 0) n += got;
    if (n > INDEX_CAP) return { kind: "oversize" };
    const text = buf.subarray(0, n).toString("utf8").replace(/\r\n/g, "\n");
    const m = text.match(/^Store: `([^`\n]*)`/m);
    return { kind: m && ABS_START.test(m[1]) ? "absolute" : "ok" };
  } catch (e) {
    return { kind: "unreadable", code: e.code ?? "EIO" };
  } finally {
    if (fd !== undefined) { try { fsio.closeSync(fd); } catch { /* already closed */ } }
  }
}
const LEGACY_MESSAGES = {
  absolute: "index footer carries an absolute path — regenerate with dod-index.mjs",
  oversize: "README.md over 1 MB — not a generated index; regenerate",
  unreadable: (l) => `cannot read README.md (${l.code})`,
};
function legacyMessage(l) { const m = LEGACY_MESSAGES[l.kind]; return typeof m === "function" ? m(l) : m; }
let renderSink = null;

function listPlans(plans) {
  if (!plans.length) return "dod: no plans";
  return plans.map((p) => { const c = checkPlan(p, plans); return `${p.slug.padEnd(28)} ${String(p.fm.status ?? "?").padEnd(12)} ${String(p.fm.size ?? "").padEnd(5)} verified ${c.verified}/${c.total}${c.problems.length ? ` · ${c.problems.length} problem(s)` : ""}${c.warnings.length ? ` · ${c.warnings.length} warning(s)` : ""}`; }).join("\n");
}

function briefLine(plans, dir, indexStale) {
  if (!existsSync(dir)) return `dod: no plan store at ${dir}`;
  const open = plans.filter((p) => ["ready", "in-progress"].includes(p.fm.status));
  const parts = open.map((p) => { const c = checkPlan(p, plans); return `${p.slug} ${p.fm.status} ${c.verified}/${c.total}`; });
  const probs = plans.reduce((n, p) => n + checkPlan(p, plans).problems.length, 0);
  return `dod: ${open.length} open${parts.length ? " — " + parts.join(" · ") : ""}${probs ? ` · ${probs} check problem(s)` : ""}${indexStale ? " · index stale (run dod-index)" : ""}`;
}

function indexIsFresh(dir, plans) {
  const f = join(dir, "README.md");
  if (!existsSync(f)) return false;
  return readFileSync(f, "utf8").replace(/\r\n/g, "\n") === renderIndex(plans, dir);
}

export function resolveStore(explicit, cwd = process.cwd()) {
  if (explicit) return resolve(cwd, explicit);
  const found = [];
  for (const f of ["CLAUDE.md", "AGENTS.md", join(".cursor", "rules", "dod.mdc")]) {
    const p = join(cwd, f);
    if (!existsSync(p)) continue;
    const m = readFileSync(p, "utf8").match(/^dod-store:[ \t]*(.+?)[ \t]*$/m);
    if (m) found.push({ file: f, dir: m[1].replace(/^["']|["']$/g, "") });
  }
  const distinct = [...new Set(found.map((x) => resolve(cwd, x.dir)))];
  if (distinct.length > 1) throw new Error(`conflicting dod-store declarations: ${found.map((x) => `${x.file} → ${x.dir}`).join("; ")}`);
  return distinct[0] ?? resolve(cwd, "docs", "dod");
}

// ---------------------------------------------------------------- selftest

// Seed a random 24-char secret into the environment before any render, so the leak scan can prove that nothing
// the script writes carries an environment value. No entropy → one fixed line, exit 1, nothing created.
function seedSecret(rb = randomBytes) {
  const had = Object.prototype.hasOwnProperty.call(process.env, "DOD_TEST_SECRET");
  const previous = process.env.DOD_TEST_SECRET;
  const value = rb(18).toString("base64url");
  process.env.DOD_TEST_SECRET = value;
  return { value, restore() { if (had) process.env.DOD_TEST_SECRET = previous; else delete process.env.DOD_TEST_SECRET; } };
}

function selftest(deps = {}) {
  let secret;
  try { secret = seedSecret(deps.randomBytes); } catch { console.log("selftest: no entropy for DOD_TEST_SECRET"); return 1; }
  const rendered = [];
  renderSink = rendered;
  const tmp = (deps.mkdtempSync ?? mkdtempSync)(join(tmpdir(), "dod-selftest-"));
  const dir = join(tmp, "docs", "dod");
  mkdirSync(dir, { recursive: true });
  const fm = (o) => "---\n" + Object.entries(o).map(([k, v]) => `${k}: ${v}`).join("\n") + "\n---\n";
  const coverage = (opts = {}) => "| # | Layer | Status | Probes | Pointer / reason |\n|---|---|---|---|---|\n" + LAYERS.map(([name, probes], i) => {
    const k = i + 1;
    if (k === 11) return `| 11 | ${name} | N/A | — | no human-facing surface: nightly job, checked src/jobs/ |`;
    if (k === opts.gap) return `| ${k} | ${name} | Gap | 1/${probes} | 6.2, 6.3 unanswered |`;
    const ptr = k === 1 || k === 15 ? name : `${name} › D1`;
    if (k === opts.noItem) return `| ${k} | ${name} | Considered | ${probes}/${probes} | ${name} |`;
    if (k === opts.wrongName) return `| ${k} | Wrong name | Considered | ${probes}/${probes} | ${ptr} |`;
    return `| ${k} | ${name} | Considered | ${probes}/${probes} | ${ptr} |`;
  }).join("\n") + `\nGate — acceptance & testability: ${opts.gap ? "failed" : "passed"}\n`;
  const sections = LAYERS.map(([n]) => `## ${n}\ntext\n`).join("\n");
  const base = { dod: 1, id: "dod-20260914-t3st", slug: "good", title: "Good plan", status: "in-progress", size: "M", parent: "none", created: "2026-09-14", baselined: "2026-09-15", closed: "none", commit: "abc1234", coverage_author: "14/14 layers · 42/42 probes", coverage_reviewer: "14/14 layers · 42/42 probes", review: "codex" };
  const good = fm(base) + `# DoD: Good plan

## Definition of Done
- [x] D1 · Export downloads as CSV · test: export.test.ts
- [ ] D2 · Lint passes with zero errors · cmd: npm run lint → 0 errors
- [ ] D3 · Duplicate export is idempotent · test: export.test.ts

${sections}
## Assumptions
- A-1 · validated · Users are authenticated · source: src/auth.ts

## Coverage
${coverage()}
## Baseline
- [ ] D1 · Export downloads as CSV · test: export.test.ts
- [ ] D2 · Lint passes · cmd: npm run lint → 0 errors

## Amendments
- A1 · 2026-09-16 · discovered · +D3 · layer: 9.3 · double-submit created two exports
- A2 · 2026-09-16 · requested · ~D2 · layer: — · user wants the lint message in the statement

## Log
- 2026-09-14 · status → draft · plan
- 2026-09-15 · status → ready · approve · review: codex
- 2026-09-15 · status → in-progress · start
- 2026-09-16 · D1 · fail · test: export.test.ts (1 fail) · abc1234 · claude
- 2026-09-16 · D1 · pass · test: export.test.ts (9 pass) · def5678 · claude
`;
  const goodReviews = `## Review 1 · 2026-09-15 · codex · plan commit abc1234\nF1 blocking: something\nF2 advisory: something else\n14/14 layers · 42/42 probes\nVERDICT: READY\n### Dispositions\n- F1 · accepted · x\n- F2 · rejected · y\n`;
  const bad = fm({ ...base, id: "dod-20260914-t3s2", slug: "bad", title: "Bad plan", status: "done", closed: "2026-09-17", review: "banana", size: "Epic", created: "2026-13-40" }) + `# DoD: Bad plan

## Definition of Done
- [x] D1 · Export downloads as CSV · test: export.test.ts
- [x] D2 · Lint passes · cmd: npm run lint → 0 errors
- [ ] D4 · Sneaked in without an amendment · file: src/x.ts
- [ ] D5 malformed line

${sections}
## Assumptions
- A-1 · decision-required · Retention period unknown
- A-2 · decison-required · misspelled type

## Coverage
${coverage({ gap: 6, noItem: 7, wrongName: 8 })}
## Baseline
- [ ] D1 · Export downloads as CSV (original wording) · test: export.test.ts
- [ ] D2 · Lint passes · cmd: npm run lint → 0 errors
- [ ] D3 · Removed later · file: x

## Amendments
- A1 · 2026-09-16 · discovered · +D2 · layer: nine · already existed
- A3 · 2026-09-15 · requested · ~D9 · layer: — · does not exist, out of sequence, earlier date
- A4 · 2026-09-16 · requested · -D3 · layer: — · drop D3
- A5 · 2026-09-16 · discovered · +D3 · layer: 10.1 · reuses a retired id; gating; never re-reviewed

## Children

## Log
- 2026-09-14 · status → draft · plan
- 2026-09-15 · status → in-progress · start
- 2026-09-16 · D1 · pass · test: export.test.ts (9 pass) · abc1234 · claude
- 2026-09-16 · D1 · fail · test: export.test.ts (1 fail) · abc1234 · claude
- 2026-09-17 · status → done · close
- 2026-09-18 · status → in-progress · reopen A99
- 2026-09-19 · status → cancelled · gave up
`;
  // a plan cancelled after approve keeps its baseline (B3) and uses the exact cancel grammar (B12)
  const term = fm({ ...base, id: "dod-20260914-t3rm", slug: "term", title: "Cancelled plan", status: "cancelled", closed: "2026-09-16" }) + `# DoD: Cancelled plan

## Definition of Done
- [ ] D1 · Export downloads as CSV · test: export.test.ts
- [ ] D2 · Lint passes · cmd: npm run lint → 0 errors
- [ ] D3 · Idempotent · test: export.test.ts

${sections}
## Assumptions
- A-1 · reversible · Page size 100 · fallback: one constant in src/export.ts

## Coverage
${coverage()}
## Baseline
- [ ] D1 · Export downloads as CSV · test: export.test.ts
- [ ] D2 · Lint passes · cmd: npm run lint → 0 errors
- [ ] D3 · Idempotent · test: export.test.ts

## Amendments

## Log
- 2026-09-14 · status → draft · plan
- 2026-09-15 · status → ready · approve · review: codex
- 2026-09-16 · status → cancelled · cancel · feature dropped from the quarter
`;
  const termReviews = `## Review 1 · 2026-09-15 · codex · plan commit abc1234\nF1 · no blocking gaps found\n14/14 layers · 42/42 probes\nVERDICT: READY\n### Dispositions\n- F1 · accepted · none needed\n`;
  // review binding (B9/B10), shrunk denominators (B6), weak assumptions (B11), duplicate id (A2), stale READY
  const bad2 = fm({ ...base, id: "dod-20260914-t3s2", slug: "bad2", title: "Bad plan 2", status: "ready", review: "codex", coverage_reviewer: "13/14 layers · 40/42 probes" }) + `# DoD: Bad plan 2

## Definition of Done
- [ ] D1 · Export downloads as CSV · test: export.test.ts
- [ ] D2 · Lint passes · cmd: npm run lint → 0 errors
- [ ] D3 · Idempotent · test: export.test.ts

${sections}
## Assumptions
- A-1 · validated · Users are authenticated
- A-2 · reversible · Page size 100

## Coverage
${coverage().replace("| 3 | Inputs, outputs & data | Considered | 4/4 |", "| 3 | Inputs, outputs & data | Considered | 2/2 |")}
## Baseline
- [ ] D1 · Export downloads as CSV · test: export.test.ts
- [ ] D2 · Lint passes · cmd: npm run lint → 0 errors
- [ ] D3 · Idempotent · test: export.test.ts

## Amendments

## Log
- 2026-09-14 · status → draft · plan
- 2026-09-15 · status → ready · approve · review: codex
`;
  const bad2Reviews = `## Review 1 · 2026-09-15 · subagent · plan commit abc1234\nF1 · fine\n14/14 layers · 42/42 probes\nVERDICT: READY\n### Dispositions\n- F1 · accepted · x\n## Review 3 · 2026-09-14 · codex\nF1 blocking · missing retention\n13/14 layers · 40/42 probes\nVERDICT: REVISE\n### Dispositions\n- F1 · rejected · y\n`;
  writeFileSync(join(dir, "good.md"), good);
  writeFileSync(join(dir, "good.reviews.md"), goodReviews);
  writeFileSync(join(dir, "bad.md"), bad);
  writeFileSync(join(dir, "term.md"), term);
  writeFileSync(join(dir, "term.reviews.md"), termReviews);
  writeFileSync(join(dir, "bad2.md"), bad2);
  writeFileSync(join(dir, "bad2.reviews.md"), bad2Reviews);
  try {
    const plans = loadPlans(dir);
    const g = checkPlan(plans.find((p) => p.slug === "good"), plans);
    const t = checkPlan(plans.find((p) => p.slug === "term"), plans);
    const b = checkPlan(plans.find((p) => p.slug === "bad"), plans);
    const b2 = checkPlan(plans.find((p) => p.slug === "bad2"), plans);
    const expectBad = [
      "with Gap layers: 6", "acceptance gate line is failed", "layer 7 is Considered but its pointer names no D-item", 'Coverage row 8 is "Wrong name"',
      "amendment drift", "D1 differs from ## Baseline", "D1 is checked without evidence", "D2 is checked without evidence", 'review "banana"',
      "A1: +D2 but D2 was already used", "A3: ~D9 but D9 does not exist", "A3: amendment ids must be sequential", "A3: date 2026-09-15 is earlier",
      "A5: +D3 but D3 was already used", "must name the layer or probe", "A5 (gating probe 10.1) has no READY review", "unverified items", "## Report is empty",
      "illegal transition draft → in-progress", "decision-required", "Definition of Done: line does not match", "Assumptions: line does not match",
      "Epic with no children", 'created "2026-13-40" is not a valid', "reopen cites A99, which does not exist",
      "cancelled transition must read", "id dod-20260914-t3s2 is also used by bad2",
    ];
    const expectBad2 = [
      "latest review (Review 3) is REVISE", "latest READY review (Review 1) was by subagent", 'coverage_reviewer "13/14 layers · 40/42 probes" ≠ Review 1',
      "Review 3: reviews must be numbered sequentially", "Review 3 is dated before Review 1", "layer 3 claims 2 probes; the rubric has 4",
      "validated needs", "reversible needs",
    ];
    const caught = expectBad.filter((s) => b.problems.some((p) => p.includes(s)));
    const caught2 = expectBad2.filter((s) => b2.problems.some((p) => p.includes(s)));
    const missed = [...expectBad.filter((s) => !caught.includes(s)), ...expectBad2.filter((s) => !caught2.includes(s))];
    const rate = g.report.rate; // baseline 2, discovered design changes 1 → 67 %
    writeFileSync(join(dir, "README.md"), renderIndex(plans, dir));
    const fresh = indexIsFresh(dir, plans);
    writeFileSync(join(dir, "README.md"), "hand edited\n");
    const stale = !indexIsFresh(dir, plans);
    writeFileSync(join(tmp, "CLAUDE.md"), "x\ndod-store: my docs/dod plans\ny\n");
    const storeOk = resolveStore(undefined, tmp) === resolve(tmp, "my docs/dod plans");

    // --- index-relative: the footer is relative in every store position and survives hostile directory names
    const footerOf = (text) => text.match(/^Store: (.*)$/m)?.[1] ?? "";
    const pathOf = (text) => footerOf(text).match(/^`([^`]*)`\./)?.[1];
    const relativeFooter = (text) => { const p = pathOf(text); return p !== undefined && !/^[A-Za-z]:[\\/]/.test(p) && !/^\/(?!\/)/.test(p) && !/^(?:\\\\|\/\/)/.test(p) && !text.includes(homedir()); };
    const cwd = resolve(sep === "\\" ? "C:\\work\\repo" : "/work/repo");
    const under = renderIndex(plans, join(cwd, "docs", "dod"), { cwd });
    const equal = renderIndex(plans, cwd, { cwd });
    const outside = renderIndex(plans, resolve(cwd, "..", "elsewhere", "dod"), { cwd });
    const hostile = renderIndex(plans, join(cwd, "docs", "a`b\nc\x1bd\x85e\u2028f\u2029g\u202Eh"), { cwd });
    const hostileFooter = footerOf(hostile);
    const driveLike = renderIndex(plans, join(cwd, "docs", "C:\\leak"), { cwd });
    const crossRoot = renderIndex(plans, "ignored", { cwd, relative: () => (sep === "\\" ? "D:\\b" : "//share/b") });
    const indexRelative = pathOf(under) === "docs/dod" && pathOf(equal) === "." && pathOf(outside)?.startsWith("../") === true
      && [under, equal, outside, hostile, driveLike].every(relativeFooter)
      && hostile.split("\n").filter((l) => l.startsWith("Store: ")).length === 1 && hostileFooter.startsWith("`docs/a'b") && !/[`\n\x1b\x85\u2028\u2029\u202E]/.test(pathOf(hostile))
      && pathOf(driveLike)?.startsWith("docs/") === true && pathOf(driveLike).includes("C:")
      && footerOf(crossRoot).startsWith(FOOTER_NO_PATH.slice("Store: ".length)) && !crossRoot.includes("share") && !crossRoot.includes("D:");

    // --- index-legacy-footer: a README written by dod ≤ 0.1.2 is warned about by --check-index and --check
    const capture = (fn) => { const out = [], err = []; const { log, error } = console; console.log = (...a) => out.push(a.join(" ")); console.error = (...a) => err.push(a.join(" ")); try { const code = fn(); return { code, out: out.join("\n"), err: err.join("\n") }; } finally { console.log = log; console.error = error; } };
    const run = (...a) => capture(() => main(["node", SELF, ...a, "--dir", dir]));
    const WARN = LEGACY_MESSAGES.absolute;
    const legacyResults = [];
    for (const abs of ["C:\\Users\\example\\repo\\docs\\dod", "/home/example/repo/docs/dod"]) {
      writeFileSync(join(dir, "README.md"), renderIndex(plans, dir).replace(/^Store: .*$/m, `Store: \`${abs}\`. Plans are the source of truth; this file is regenerated.`));
      const ci = run("--check-index"), ck = run("--check", "good");
      legacyResults.push(ci.code === 1 && ci.out.includes(WARN) && ck.code === 0 && ck.out.includes(`warn: ${WARN}`));
    }
    const regen = run();
    const after = [run("--check-index"), run("--check", "good")];
    legacyResults.push(regen.code === 0 && after[0].code === 0 && !after[0].out.includes(WARN) && after[1].code === 0 && !after[1].out.includes("warn: index footer"));
    // sub-case oversize-index: 1 MB + 1 byte → refused before any read
    writeFileSync(join(dir, "README.md"), Buffer.alloc(INDEX_CAP + 1, 0x20));
    const realRead = fsio.readSync; let reads = 0; fsio.readSync = (...a) => { reads++; return realRead(...a); };
    const oversize = run("--check-index");
    fsio.readSync = realRead;
    legacyResults.push(oversize.code === 1 && oversize.out.includes(LEGACY_MESSAGES.oversize) && reads === 0);
    // sub-case invalid-utf8-index: a 0xFF byte inside the footer → stale, no crash, no legacy warning
    const goodIndex = renderIndex(plans, dir);
    const k = goodIndex.indexOf(". Plans are the source");
    writeFileSync(join(dir, "README.md"), Buffer.concat([Buffer.from(goodIndex.slice(0, k), "utf8"), Buffer.from([0xff]), Buffer.from(goodIndex.slice(k), "utf8")]));
    const badUtf8 = run("--check-index");
    legacyResults.push(badUtf8.code === 1 && badUtf8.out.includes("STALE") && !badUtf8.out.includes(WARN));
    // sub-case unreadable-index: the open fails with EACCES → --check-index reports and exits 1; --check warns and continues
    const realOpen = fsio.openSync; fsio.openSync = () => { const e = new Error("EACCES: permission denied"); e.code = "EACCES"; throw e; };
    const unreadableCi = run("--check-index"), unreadableCk = run("--check", "good");
    fsio.openSync = realOpen;
    legacyResults.push(unreadableCi.code === 1 && unreadableCi.err.includes("dod index: cannot read README.md (EACCES)") && unreadableCk.code === 0 && unreadableCk.out.includes("warn: cannot read README.md (EACCES)"));
    const legacyFooterOk = legacyResults.every(Boolean);
    writeFileSync(join(dir, "README.md"), renderIndex(plans, dir));

    // --- leak-scan: nothing rendered by any fixture above carries the home directory, the temp dir or the seeded secret
    const needles = { secret: secret.value, tmpdir: tmp };
    try { needles.tmpdir_real = realpathSync(tmp); } catch { /* keep the unresolved path only */ }
    try { const h = homedir(); if (h) needles.home = h; else throw new Error("empty"); } catch { console.log("leak-scan: no home directory on this host — needle skipped"); }
    const leaks = scanForLeaks(rendered.join("\n"), needles);
    const planted = scanForLeaks(`${rendered[0]}\n${secret.value}`, needles);
    const boundary = scanForLeaks("Store: `../..//tmp/x`", { tmpdir: "/tmp/x" }).length === 0 && scanForLeaks("Store: `/tmp/x`", { tmpdir: "/tmp/x" }).length === 1;
    const separators = scanForLeaks(`Store: \`${tmp.split(sep).join("/")}/docs/dod\`.`, needles).includes("tmpdir");
    const noEntropy = capture(() => selftest({ randomBytes: () => { throw new Error("no entropy"); }, mkdtempSync: () => { throw new Error("must not be reached"); } }));
    const t0 = performance.now();
    const many = Array.from({ length: 400 }, (_, i) => rendered[0].replace("# Definition of Done — index", `# Definition of Done — index ${i}`));
    const manyLeaks = many.reduce((n, text) => n + scanForLeaks(text, needles).length, 0);
    console.log(`leak-scan: 400 files in ${Math.round(performance.now() - t0)} ms`);
    const leakScan = rendered.length >= 8 && leaks.length === 0 && boundary && separators && planted.length === 1 && planted[0] === "secret" && manyLeaks === 0
      && noEntropy.code === 1 && noEntropy.out.trim() === "selftest: no entropy for DOD_TEST_SECRET" && process.env.DOD_TEST_SECRET === secret.value;

    const ok = g.problems.length === 0 && t.problems.length === 0 && missed.length === 0 && rate === 67 && fresh && stale && g.verified === 1 && storeOk && indexRelative && legacyFooterOk && leakScan;
    console.log(`selftest: known-good problems=${g.problems.length} verified=${g.verified}/${g.total} rate=${rate}%  cancelled-after-ready problems=${t.problems.length}  known-bad caught ${caught.length + caught2.length}/${expectBad.length + expectBad2.length}  index fresh=${fresh} stale-detected=${stale}  store-with-spaces=${storeOk}  index-relative=${indexRelative} legacy-footer=${legacyFooterOk} leak-scan=${leakScan}`);
    if (!ok) {
      console.log("  index-relative:", { under: footerOf(under), equal: footerOf(equal), outside: footerOf(outside), hostile: hostileFooter, driveLike: footerOf(driveLike), crossRoot: footerOf(crossRoot) });
      console.log("  legacy-footer:", legacyResults, "leak-scan:", { rendered: rendered.length, leaks, planted, manyLeaks, noEntropy }); console.log("  good problems:", g.problems); console.log("  term problems:", t.problems); console.log("  bad problems:", b.problems); console.log("  bad2 problems:", b2.problems); console.log("  expectations missed:", missed); }
    return ok ? 0 : 1;
  } finally {
    renderSink = null;
    secret.restore();
    rmSync(tmp, { recursive: true, force: true });
  }
}

// ---------------------------------------------------------------- cli

function main(argv) {
  const args = argv.slice(2);
  const opt = (name) => { const k = args.indexOf(name); return k === -1 ? undefined : args[k + 1]; };
  if (args.includes("--selftest")) return selftest();
  let dir;
  try { dir = resolveStore(opt("--dir")); } catch (e) { console.error(`dod: ${e.message}`); return args.includes("--brief") ? 0 : 1; }
  const plans = loadPlans(dir);

  if (args.includes("--brief")) { console.log(briefLine(plans, dir, existsSync(dir) && !indexIsFresh(dir, plans))); return 0; }
  if (!existsSync(dir)) { console.error(`no plan store at ${dir} — run the dod skill's setup, or pass --dir`); return 1; }
  if (args.includes("--list")) { console.log(listPlans(plans)); return 0; }

  if (args.includes("--check-index")) {
    const legacy = legacyFooter(dir);
    if (legacy.kind === "unreadable") { console.error(`dod index: ${legacyMessage(legacy)}`); return 1; }
    if (legacy.kind === "oversize") { console.log(`dod index: ${legacyMessage(legacy)}`); return 1; }
    if (legacy.kind === "absolute") console.log(`dod index: ${legacyMessage(legacy)}`);
    const fresh = indexIsFresh(dir, plans);
    console.log(fresh ? "dod index: fresh" : "dod index: STALE or missing — regenerate with dod-index.mjs");
    return fresh ? 0 : 1;
  }
  const slug = opt("--check");
  if (slug) {
    const plan = plans.find((p) => p.slug === slug);
    if (!plan) { console.error(`no plan ${slug} in ${dir}`); return 1; }
    const c = checkPlan(plan, plans);
    const r = c.report;
    console.log(`${slug} · ${plan.fm.status} · verified ${c.verified}/${c.total}`);
    console.log(`  baseline ${r.baseline} · discovered ${r.discovered} amendment(s) / ${r.discoveredDesign} design change(s) · requested ${r.requested} · defect ${r.defect} · external ${r.external}` + (r.rate == null ? "" : ` · prediction rate ${r.rate} %`));
    const legacy = legacyFooter(dir);
    if (legacy.kind !== "ok") console.log(`  warn: ${legacyMessage(legacy)}`);
    for (const w of c.warnings) console.log(`  warn: ${w}`);
    for (const p of c.problems) console.log(`  ✗ ${p}`);
    return c.problems.length ? 1 : 0;
  }
  writeFileSync(join(dir, "README.md"), renderIndex(plans, dir));
  console.log(`dod index: wrote ${join(dir, "README.md")} (${plans.length} plan(s))`);
  console.log(briefLine(plans, dir, false));
  return 0;
}

if (process.argv[1] && resolve(process.argv[1]) === SELF) process.exit(main(process.argv));
